server:
  port: 8801
spring:
  datasource:
    driver-class-name: ${jdbc.driver}
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}

mybatis-plus:
  mapper-locations: classpath*:/Mapper/*Mapper.xml
  type-aliases-package: com.demo.DoMain # 类别名包扫描
  configuration:
    call-setters-on-nulls: true   # 当查询到的字段为空是,是否调用set方法对属性进行Null值的初始化
    local-cache-scope: session  # 默认为session级别缓存,STATEMENT:关闭一级缓存
    cache-enabled: true   #是否开启二级缓存,默认为true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL
  global-config:  # 全局配置
    banner: false   # 是否控制台输出 MybatisPlus的LOGO

logging:
  level:
    cn.itcast: info
    org.springframework: info